name: Feature/Texture suggestion
description: Pitch your idea for BetterBlockZ
title: "[Suggestion] "
labels: [enhancement]

body:
  - type: dropdown
    id: suggestion-type
    attributes:
      label: Type of suggestion
      description: Choose the category that best fits your idea
      options:
        - New texture
        - CTM support
        - Texture correction
        - Block variation
        - Other
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: Suggestion details
      description: Describe your feature or texture suggestion.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: Add screenshots or mockups if you have them.
